### ISSUE TITLE
機能要望：HBBR起動時、指定監視フォルダ内に既に存在するファイルをHBBRキューに自動で追加する機能

### ISSUE THREAD

**Issue by ghost** [Suzumebati/HandbreakBatchRunner#1]
こんにちは、素晴らしいアプリをリリースして下さってありがとうございます。いつも便利に使わせて頂いております。

フォルダ監視機能についての要望なのですが、現在の仕様ではHBBR起動中、監視フォルダに新たなファイルが追加された時だけHBBRキューに追加される仕様となっていますが、HBBR起動時に監視フォルダ内に既にファイルが存在する場合、それらも自動でHBBRキューに追加してくれるように出来るオプションが欲しいです。（例えば、処理を実行中に何らかの原因でPCやHBBRが再起動した場合等に、自動で処理を再開出来るようにして欲しいので）

**Comment by ghost** [comment]
また、何らかの原因でHBBRキューに追加された処理が失敗やスキップされてしまった場合、自動で再試行してくれるオプションや、
何らかの原因で監視フォルダからHBBRキューリストへの追加漏れが発生してしまった場合、何かのトリガーで（例えば指定時間起きに処理漏れが無いかチェックする等）自動で追加するようなオプション等もあったらな…と思います。

**Comment by Suzumebati** [comment]
はじめまして自分ツールとして作っちゃってますが便利に使ってくれているのなら何よりです！

まず簡単なのは起動時に変換フォルダ内に残っているファイルを変換対象に入れるオプションを加えることですね。
完了状態のリトライは正常に終わったかの判定を残して異常終了したものだけまわして
リトライは何回までやるのか…など考えることが多いのでコードに手を入れる範囲が広めです。
それはそれで別で要望として考えようとかなと思います。

**Comment by ghost** [comment]
お忙しい中、ご返信ありがとうございます！

>まず簡単なのは起動時に変換フォルダ内に残っているファイルを変換対象に入れるオプションを加えることですね。

現状、個人的にはこちらの機能が付くだけで大大大満足なので、お手すきの際に実装でもしていただけるのでしたら、めっちゃ嬉しいです！

>完了状態のリトライは正常に終わったかの判定を残して異常終了したものだけまわして
>リトライは何回までやるのか…など考えることが多いのでコードに手を入れる範囲が広めです。
>それはそれで別で要望として考えようとかなと思います。

こちらに関しては、正直「他に強いて言うなら…」と思いつきで言ってみたようなものなので、もし実装にお手間がかかるようでしたら、どうか何卒、ご無理をなさらないようお願い致します。（軽い気持ちで発言してしまい、申し訳ありませんでした。）

これらの機能が実装されるにしろされないにしろ、これからもこちらのアプリを有り難くお借りさせて頂きたいと思います。
こんな素敵なアプリを一般に公開して下さり、ありがとうございました。

**Comment by Suzumebati** [comment]
ということで起動時に監視フォルダ内のファイルを追加するオプション機能を実装して
V1.0.5をリリースしました！

完了までリトライする件はまた他の要望あれば考えますね～
また何かありましたらできる範囲では対応したいと思ってます＼(^o^)／

**Comment by ghost** [comment]
お忙しい中お早いリリースありがとうございます！お疲れ様です！
新しいオプションですが、いい感じに動いてます！
これで自動エンコがますます捗ります！本当にありがとうございます！

ちなみになのですが、もしもこの先仮に、こちらのアプリで不具合？的な挙動を発見した場合は、その時は積極的にご報告しても大丈夫でしたでしょうか？
（元はご自身用に開発されたものとのことで、あまり積極的にそういうものを求めてなかったら申し訳ありません）

**Comment by Suzumebati** [comment]
ご希望のものになったようで良かったです！

フィードバックは基本ウェルカムですが、結構ゆるくやってるところあるで、
こりゃいかんってやつは対応したいなって思ってますが、細かなのが多く出ると全ては対応できないかも…って感じなので
全対応をお望みじゃなければOK〜って感じです(・・;

**Comment by ghost** [comment]
ご返信ありがとうございます、承知しました！
あれから毎日使用していますが、相変わらずいい感じです！
また何かありましたらご連絡させて頂きます、この度は本当にありがとうございました！
今後も開発応援しております、頑張って下さい！

**Comment by Suzumebati** [comment]
こちらも一人で開発して使ってると、こういうもんだなということで
なかなか新しい要望が出てこないので刺激になりました！こちらこそありがとうございました。

ということでクローズしておきます！
